import { Component } from '@angular/core';

@Component({
  selector: 'app-pessoas-pesquisa',
  templateUrl: './pessoas-pesquisa.component.html',
  styleUrls: ['./pessoas-pesquisa.component.scss']
})
export class PessoasPesquisaComponent {
  value = '';

  products: any[] = [
    {
      id: '1010',
      code: 'qwe34sdg',
      name: 'Laptop Pro',
      description: 'High-performance laptop',
      image: 'laptop-pro.jpg',
      price: 2500.0,
      category: 'Computers',
      quantity: 15,
      inventoryStatus: 'RECEITA',
      rating: 4,
    },
    {
      id: '1020',
      code: 'yui78khj',
      name: 'Gaming Chair',
      description: 'Ergonomic chair for gaming',
      image: 'gaming-chair.jpg',
      price: 199.99,
      category: 'Furniture',
      quantity: 8,
      inventoryStatus: 'DESPESA',
      rating: 5,
    },
    {
      id: '1030',
      code: 'zxc90vbn',
      name: 'Wireless Mouse',
      description: 'Smooth and responsive mouse',
      image: 'wireless-mouse.jpg',
      price: 29.99,
      category: 'Accessories',
      quantity: 30,
      inventoryStatus: 'RECEITA',
      rating: 4,
    },
    {
      id: '1040',
      code: 'asd34ghj',
      name: 'Smartphone XL',
      description: 'Latest smartphone with big screen',
      image: 'smartphone-xl.jpg',
      price: 899.99,
      category: 'Phones',
      quantity: 25,
      inventoryStatus: 'RECEITA',
      rating: 5,
    },
    {
      id: '1050',
      code: 'fgh56klm',
      name: 'Noise Cancelling Headphones',
      description: 'Best-in-class noise cancellation',
      image: 'headphones.jpg',
      price: 299.99,
      category: 'Audio',
      quantity: 10,
      inventoryStatus: 'DESPESA',
      rating: 5,
    },
    {
      id: '1060',
      code: 'jkl23zxc',
      name: 'Smartwatch Series 5',
      description: 'Wearable smart device',
      image: 'smartwatch.jpg',
      price: 399.99,
      category: 'Accessories',
      quantity: 20,
      inventoryStatus: 'RECEITA',
      rating: 4,
    },
    {
      id: '1070',
      code: 'vbn56mnb',
      name: '4K Ultra HD TV',
      description: 'Crisp and clear 4K TV',
      image: '4k-tv.jpg',
      price: 1200.0,
      category: 'Electronics',
      quantity: 5,
      inventoryStatus: 'RECEITA',
      rating: 5,
    },
    {
      id: '1080',
      code: 'qaz67plm',
      name: 'Bluetooth Speaker',
      description: 'Portable and powerful speaker',
      image: 'bluetooth-speaker.jpg',
      price: 89.99,
      category: 'Audio',
      quantity: 18,
      inventoryStatus: 'DESPESA',
      rating: 4,
    },
    {
      id: '1070',
      code: 'vbn56mnb',
      name: '4K Ultra HD TV',
      description: 'Crisp and clear 4K TV',
      image: '4k-tv.jpg',
      price: 1200.0,
      category: 'Electronics',
      quantity: 5,
      inventoryStatus: 'RECEITA',
      rating: 5,
    },
    {
      id: '1080',
      code: 'qaz67plm',
      name: 'Bluetooth Speaker',
      description: 'Portable and powerful speaker',
      image: 'bluetooth-speaker.jpg',
      price: 89.99,
      category: 'Audio',
      quantity: 18,
      inventoryStatus: 'DESPESA',
      rating: 4,
    },
  ];

  constructor() {}

}
